name: Checks

on:
  push:
  pull_request:
    branches:
      - main
      - 'release/**'
      - 'develop/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install black
        run: pip install black[jupyter]==23.12.1
      - name: Run black to reformat code
        run: black . --extend-exclude ".*thirdparty.*"
      - name: Show changes made by black
        run: git diff --color

  size_t:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Check
        run: >
          CI/check_size_t.py . --exclude "thirdparty/*"
