name: Update Requirements

on:
  push:

jobs:
  update-python-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Compile requirements.txt
#        run: pip-compile --output-file=docs/requirements.txt docs/requirements.in
        run: pip-compile docs/requirements.in > docs/requirements.txt

      - name: Detect changes
        id: changes
        run:
          # This output boolean tells us if the dependencies have actually changed
          echo "count=$(git status --porcelain=v1 2>/dev/null | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit updated requirements.txt
        # Only push if changes exist
        if: steps.changes.outputs.count > 0
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Weekly Update: Regenerate requirements.txt"
          git push -f origin ${{ github.ref_name }}:$BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
