name: Update Requirements

on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Compile requirements.txt
        run: pip-compile --output-file=docs/requirements.txt docs/requirements.in

#      - name: Commit updated requirements.txt
#        run: |
#          git config user.name "github-actions[bot]"
#          git config user.email "github-actions[bot]@users.noreply.github.com"
#          git add requirements.txt
#          git commit -m "Weekly Update: Regenerate requirements.txt"
#          git push
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
