name: Update Requirements

on:
  push:

jobs:
  check_pr_labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
          dot: true

#jobs:
#  update:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.12
#
#      - name: Install pip-tools
#        run: pip install pip-tools
#
#      - name: Compile requirements.txt
#        run: pip-compile docs/requirements.in > docs/requirements.txt
#
#      - name: Commit updated requirements.txt
#        run: |
#          git config user.name "github-actions[bot]"
#          git config user.email "github-actions[bot]@users.noreply.github.com"
#          git add requirements.txt
#          git commit -m "Weekly Update: Regenerate requirements.txt"
#          git push
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
